In [1]:
#1
class Student:
  ID = 0
  def __init__(self,name,dept,age,cgpa):
    Student.ID += 1
    self.name = name
    self.cgpa = cgpa
    self.dept = dept
    self.age = age
  def showDetails(self):
    print(f"Id: {Student.ID}")
    print(f"Name: {self.name}")
    print(f"Department: {self.dept}")
    print(f"Age: {self.age}")
    print(f"CGPA: {self.cgpa}")
  @classmethod
  def from_String(cls,string):
    cls.ID += 1
    lst = string.split("-")
    name = lst[0]
    dept = lst[1]
    age = lst[2]
    cgpa = lst[3]
    return cls(name,dept,age,cgpa)


s1 = Student("Samin", "CSE", 21, 3.91)
s1.showDetails()
print("-----------------------")
s2 = Student("Fahim", "ECE", 21, 3.85)
s2.showDetails()
print("-----------------------")
s3 = Student("Tahura", "EEE", 22, 3.01)
s3.showDetails()
print("-----------------------")
s4 = Student.from_String("Sumaiya-BBA-23-3.96")
s4.showDetails()

Id: 1
Name: Samin
Department: CSE
Age: 21
CGPA: 3.91
-----------------------
Id: 2
Name: Fahim
Department: ECE
Age: 21
CGPA: 3.85
-----------------------
Id: 3
Name: Tahura
Department: EEE
Age: 22
CGPA: 3.01
-----------------------
Id: 5
Name: Sumaiya
Department: BBA
Age: 23
CGPA: 3.96

In [ ]:
#2
class Passenger:
  count=0
  def __init__(self,n,):
    self.name=n
    self.fare=450
    Passenger.count+=1

  def set_bag_weight(self,num):
    self.weight=num
    if 21<=self.weight<=50:
      self.fare+=50

    elif self.weight>50:
      self.fare+=100

  def printDetail(self):
    print(f"Name:{self.name}")
    print(f"Bus Fare:{self.fare}")


print("Total Passenger:", Passenger.count)
p1 = Passenger("Jack")
p1.set_bag_weight(90)
p2 = Passenger("Carol")
p2.set_bag_weight(10)
p3 = Passenger("Mike")
p3.set_bag_weight(25)
print("=========================")
p1.printDetail()
print("=========================")
p2.printDetail()
print("=========================")
p3.printDetail()
print("=========================")
print("Total Passenger:", Passenger.count)

Total Passenger: 0
=========================
Name:Jack
Bus Fare:550
=========================
Name:Carol
Bus Fare:450
=========================
Name:Mike
Bus Fare:500
=========================
Total Passenger: 3

In [ ]:
#3
class Travel:
  count = 0
  def __init__(self,source,to):
    Travel.count += 1
    self.source = source
    self.to = to
    self.time = "1:00"
  def set_time(self,time):
    self.time = f"{time}:00"
  def set_destination(self,to):
    self.to = to
  def set_source(self,source):
    self.source = source
  def display_travel_info(self):
    print(f"Source: {self.source}")
    print(f"Destination: {self.to}")
    print(f"Flight Time:{self.time}")

print("No. of Traveller =", Travel.count)
print("=======================")
t1 = Travel("Dhaka","India")
print(t1.display_travel_info())
print("=======================")
t2 = Travel("Kuala Lampur","Dhaka")
t2.set_time(23)
print(t2.display_travel_info())
print("=======================")
t3 = Travel("Dhaka","New_Zealand")
t3.set_time(15)
t3.set_destination("Germany")
print(t3.display_travel_info())
print("=======================")
t4 = Travel("Dhaka","India")
t4.set_time(9)
t4.set_source("Malaysia")
t4.set_destination("Canada")
print(t4.display_travel_info())
print("=======================")
print("No. of Traveller =", Travel.count)

In [ ]:
#4
class Student:
  total=0
  BracStudents=0
  otherStudents=0
  def __init__(self,n,d,uni="BRAC University"):
    self.name=n
    self.dept=d
    self.uni=uni
    Student.total+=1
    if self.uni=="BRAC University":
      Student.BracStudents+=1
    else:
      Student.otherStudents+=1

  def individualDetail(self):
    print(f"Name: {self.name}")
    print(f"Department: {self.dept}")
    print(f"Institution: {self.uni}")

  @classmethod
  def printDetails(cls):
    print(f"Total Student(s):{cls.total}")
    print(f"BRAC University Student(s): {cls.BracStudents}")
    print(f"Other Institution Student(s):{cls.otherStudents}")

  @classmethod
  def createStudent(cls,p,d,uni="BRAC University"):
    return cls(p,d,uni)


Student.printDetails()
print('#########################')

mikasa = Student('Mikasa Ackerman', "CSE")
mikasa.individualDetail()
print('------------------------------------------')
Student.printDetails()

print('========================')

harry = Student.createStudent('Harry Potter', "Defence Against Dark Arts", "Hogwarts School")
harry.individualDetail()
print('-------------------------------------------')
Student.printDetails()

print('=========================')

levi = Student.createStudent("Levi Ackerman", "CSE")
levi.individualDetail()
print('--------------------------------------------')
Student.printDetails()

Total Student(s):0
BRAC University Student(s): 0
Other Institution Student(s):0
#########################
Name: Mikasa Ackerman
Department: CSE
Institution: BRAC University
------------------------------------------
Total Student(s):1
BRAC University Student(s): 1
Other Institution Student(s):0
========================
Name: Harry Potter
Department: Defence Against Dark Arts
Institution: Hogwarts School
-------------------------------------------
Total Student(s):2
BRAC University Student(s): 1
Other Institution Student(s):1
=========================
Name: Levi Ackerman
Department: CSE
Institution: BRAC University
--------------------------------------------
Total Student(s):3
BRAC University Student(s): 2
Other Institution Student(s):1

In [ ]:
#Tracing
class A:
 temp = 4
 def __init__(self):
  self.y = self.temp - 2
  self.sum = self.temp + 1
  A.temp -= 2
  self.methodA(3, 4)
 def methodA(self, m, n):
  x = 0
  self.y = self.y + m + (self.temp)
  A.temp += 1
  x = x + 1 + n
  self.sum = self.sum + x + self.y
  print(x, self.y, self.sum)

class B:
 x = 0
 def __init__(self, b = None):
    self.y, self.temp, self.sum = 5, -5, 2

    if b == None:
      self.y = self.temp + 3

      self.sum = 3 + self.temp + 2
      self.temp -= 2
    else:
      self.sum = b.sum
      B.x = b.x
      b.methodB(2, 3)
 def methodA(self, m, n):
  x = 2
  self.y = self.y + m + (self.temp)
  self.temp += 1
  x = x + 5 + n
  self.sum = self.sum + x + self.y
  print(x, self.y, self.sum)
 def methodB(self, m, n):
  y = 0
  y = y + self.y
  B.x = self.y + 2 + self.temp
  self.methodA(self.x, y)
  self.sum = self.x + y + self.sum
  print(self.x, y, self.sum)
a1 = A()
b1 = B()
b2 = B(b1)
b1.methodA(1,2)
b2.methodB(3,2)