In [ ]:
#1
class NikeBangladesh:
  branch=[]
  total=0
  stocks={'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}

  def __init__(self,n):
    self.name=n
    self.instock={'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
    self.total=0
    NikeBangladesh.branch.append(n)

  def details(self):
    print(f"Nike {self.name} outlet:")
    print("Products Currently Stocked:")
    print(f"{self.instock}")
    print(f"Sold: {self.total}")

  def restockProducts(self,r):
    for k,v in r.items():
      self.instock[k]+=v
      NikeBangladesh.stocks[k]+=v

  def productSold(self,p):
    for k,v in p.items():
      self.instock[k]-=v
      NikeBangladesh.stocks[k]-=v
      NikeBangladesh.total+=v
      self.total+=v



  @classmethod
  def status(cls):
    print("Nike Bangladesh Status:")
    print(f"Branches Opened: {cls.branch}")
    print("Currently Stocked")
    print(f"{cls.stocks}")
    print(f"Sold: {cls.total}")


#DRIVER CODE
print("xxxxxxxxxxxxxx1xxxxxxxxxxxxxxxx")
NikeBangladesh.status()
dhaka = NikeBangladesh("Dhaka Banani")
chittagong = NikeBangladesh("Chittagong GEC")
print("xxxxxxxxxxxxxx2xxxxxxxxxxxxxxxx")
dhaka.details()
print("xxxxxxxxxxxxxx3xxxxxxxxxxxxxxxx")
chittagong.details()
print("xxxxxxxxxxxxxx4xxxxxxxxxxxxxxxx")
dhaka.restockProducts(
{"Air Jordan":1200,"Cortez":200,"Zoom Kobe":200})
chittagong.restockProducts(
{"Air Jordan":1000,"Cortez":250,"Zoom Kobe":100})
print("xxxxxxxxxxxxxx5xxxxxxxxxxxxxxxx")
NikeBangladesh.status()
print("xxxxxxxxxxxxxx6xxxxxxxxxxxxxxxx")
dhaka.productSold({"Air Jordan":760,"Cortez":90})
chittagong.productSold({"Air Jordan":520,"Zoom Kobe":70})
print("xxxxxxxxxxxxxx7xxxxxxxxxxxxxxxx")
NikeBangladesh.status()

xxxxxxxxxxxxxx1xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened: []
Currently Stocked
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx2xxxxxxxxxxxxxxxx
Nike Dhaka Banani outlet:
Products Currently Stocked:
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx3xxxxxxxxxxxxxxxx
Nike Chittagong GEC outlet:
Products Currently Stocked:
{'Air Jordan': 0, 'Cortez': 0, 'Zoom Kobe': 0}
Sold: 0
xxxxxxxxxxxxxx4xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxx5xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened: ['Dhaka Banani', 'Chittagong GEC']
Currently Stocked
{'Air Jordan': 2200, 'Cortez': 450, 'Zoom Kobe': 300}
Sold: 0
xxxxxxxxxxxxxx6xxxxxxxxxxxxxxxx
xxxxxxxxxxxxxx7xxxxxxxxxxxxxxxx
Nike Bangladesh Status:
Branches Opened: ['Dhaka Banani', 'Chittagong GEC']
Currently Stocked
{'Air Jordan': 920, 'Cortez': 360, 'Zoom Kobe': 230}
Sold: 1440

In [ ]:
#2
class Player:
  total=0
  temp=""
  def __init__(self,n=None,num=10,t=None):
    self.name=n
    self.number=num
    self.team=t
    Player.total+=1
    if n!=None:
      Player.temp+=n + ", "

  def set_name(self,p):
    self.name=p
    Player.temp+=p+", "

  def set_team(self,t):
    self.team=t
    return self.team

  def set_number(self,num):
    self.number=num
    return self.number

  def player_detail(self):
    return(f'Player Name: {self.name} \nJersey Number: {self.number} \nCountry: {self.team}')

  @classmethod
  def info(cls):
    print(f"Total number of players: {cls.total}")
    print(f"Players enlisted so far: {cls.temp[0:len(cls.temp)-2]}")



#DRIVER CODE
print("Total number of players:", Player.total)
print("---------------------------")
p1 = Player()
p1.set_name("Neymar")
p1.set_team("Brazil")
print(p1.player_detail())
print('========================')
Player.info()
print("---------------------------")
p2 = Player("Ronaldo")
p2.set_number(7)
p2.set_team("Portugal")
print(p2.player_detail())
print('========================')
Player.info()
print("---------------------------")
p3 = Player("Messi")
p3.set_team("Argentina")
print(p3.player_detail())
print('========================')
Player.info()
print("---------------------------")
p4 = Player("Mbappe", 10, "France")
print(p4.player_detail())
print('========================')
Player.info()

Total number of players: 0
---------------------------
Player Name: Neymar
Jersey Number: 10
Country: Brazil
========================
Total number of players: 1
Players enlisted so far: Neymar
---------------------------
Player Name: Ronaldo
Jersey Number: 7
Country: Portugal
========================
Total number of players: 2
Players enlisted so far: Neymar, Ronaldo
---------------------------
Player Name: Messi
Jersey Number: 10
Country: Argentina
========================
Total number of players: 3
Players enlisted so far: Neymar, Ronaldo, Messi
---------------------------
Player Name: Mbappe
Jersey Number: 10
Country: France
========================
Total number of players: 4
Players enlisted so far: Neymar, Ronaldo, Messi, Mbappe

In [ ]:
#3
class SultansDine:
  branch=0
  total=0
  name=[]
  def __init__(self,n):
    self.name=n
    self.total=0
    SultansDine.branch+=1
    SultansDine.name.append(self)
  def sellQuantity(self,q):
    self.quantity=q
    if q<10:
      self.total+= q*300
      SultansDine.total+=q*300
    elif 10<=q<=20:
      self.total+=q*350
      SultansDine.total+=q*350
    else:
      self.total+=q*400
      SultansDine.total+=q*400

  def branchInformation(self):
    print(f"Branch Name: {self.name}")
    print(f"Branch Sell: {self.total} Taka")

  @classmethod
  def details(cls):
    print(f"Total Number of branch(s): {cls.branch}")
    print(f"Total Sell: {cls.total} Taka")

    for i in cls.name:
      print(f"Branch Name: {i.name}, Branch Sell: {i.total} Taka")
      print(f"Branch consists of total sell's: {((i.total/cls.total)* 100):.2f} %")


#DRIVER CODE
SultansDine.details()
print('########################')
dhanmondi = SultansDine('Dhanmondi')
dhanmondi.sellQuantity(25)
dhanmondi.branchInformation()
print('-----------------------------------------')
SultansDine.details()
print('========================')
baily_road = SultansDine('Baily Road')
baily_road.sellQuantity(15)
baily_road.branchInformation()
print('-----------------------------------------')
SultansDine.details()
print('========================')
gulshan = SultansDine('Gulshan')
gulshan.sellQuantity(9)
gulshan.branchInformation()
print('-----------------------------------------')
SultansDine.details()

Total Number of branch(s): 0
Total Sell: 0 Taka
########################
Branch Name: Dhanmondi
Branch Sell: 10000 Taka
-----------------------------------------
Total Number of branch(s): 1
Total Sell: 10000 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 100.00 %
========================
Branch Name: Baily Road
Branch Sell: 5250 Taka
-----------------------------------------
Total Number of branch(s): 2
Total Sell: 15250 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 65.57 %
Branch Name: Baily Road, Branch Sell: 5250 Taka
Branch consists of total sell's: 34.43 %
========================
Branch Name: Gulshan
Branch Sell: 2700 Taka
-----------------------------------------
Total Number of branch(s): 3
Total Sell: 17950 Taka
Branch Name: Dhanmondi, Branch Sell: 10000 Taka
Branch consists of total sell's: 55.71 %
Branch Name: Baily Road, Branch Sell: 5250 Taka
Branch consists of total sell's: 29.25 %
Branch Name: Gulshan, Branch Sell: 2700 Taka
Branch consists of total sell's: 15.04 %